////
// URLS
////
export const CLOUD_URL = 'https://chessify.me';
export const SOCKET_URL = 'wss://chessify.me';

////
// APP CONSTANTS
////
export const VIDEOS_COUNT_PER_PAGE = 4;

export const ENGINES = {
  stockfish10: 'Stockfish 16',
  Stockfish: 'Stockfish 16',
  asmfish: 'asmFish',
  sugar: 'SugaR',
  lc0: 'LCZero 0.31-dev',
  berserk: 'Berserk 12',
  koivisto: 'Koivisto',
  rubichess: 'RubiChess',
  shashchess: 'ShashChess',
  komodo: 'Komodo D3.2',
};

export const GUEST_USER_ENGINES_OPTION = {
  lc0: {
    cpuct: {
      type: 'number',
      options: [1.745],
      description:
        '\n            Higher values promote more exploration/wider search. \n            ',
      valid_range: [0, 100],
    },
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
    network: {
      type: 'option',
      options: [
        'latest-320x24',
        'latest-512x20',
        'latest-384x30',
        'J104.1-30',
        'BT2-3650000',
        'BT3-768x15',
        'BT4-1024x15',
      ],
      description:
        '\n            Larger Neural Network means lower nps, but better evaluation per node.\n            ',
    },
    contempt: {
      type: 'number',
      options: [0],
      description: '\n            Contempt value [0, 100]. \n            ',
      valid_range: [0, 100],
    },
  },
  rubichess: {
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  stockfish10: {
    engine: {
      type: 'option',
      options: ['Stockfish 16', 'CorChess'],
      description: '\n            Select an engine to run.\n            ',
    },
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  berserk: {
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  koivisto: {
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  sugar: {
    engine: {
      type: 'option',
      options: ['Sugar AI', 'Sugar AI ICCF'],
      description: '\n            Select an engine to run.\n            ',
    },
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  asmfish: {
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
  shashchess: {
    syzygy: {
      type: 'boolean',
      options: [false, true],
      description: '\n            Use Syzygy 6 pieces TB.\n            ',
    },
  },
};

export const GUEST_USER_AVAILABLE_SERVERS = [
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 33,
    price_per_minute: 0,
    for_guests: false,
    cluster: false,
    state: 'VM is permanent',
    state_stoppable: true,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 8,
    price_per_minute: 0,
    for_guests: true,
    cluster: false,
    state: 'VM is permanent',
    state_stoppable: true,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 163,
    price_per_minute: 20,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 161,
    price_per_minute: 20,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 512,
    price_per_minute: 80,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 513,
    price_per_minute: 80,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 512,
    price_per_minute: 80,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 512,
    price_per_minute: 80,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 128,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 352,
    price_per_minute: 60,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 128,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 128,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 160,
    price_per_minute: 20,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 128,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 28,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 100,
    price_per_minute: 10,
    for_guests: false,
    cluster: false,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
  {
    cores: 30,
    price_per_minute: 0,
    for_guests: false,
    cluster: true,
    state: 'VM deallocated',
    state_stoppable: false,
  },
];
